spring.application.name=Tailora
spring.profiles.active=dev


# =====================================================
# Email Configuration 
# =====================================================
tailora.app.sendermail=kkarun701@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kkarun701@gmail.com
spring.mail.password=wvhkelngfutfugcr
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true

# =====================================================
# JWT App Properties
# =====================================================

tailora.app.jwtSecret= fjfajfinqffniafnwnfnifwnfijqwfwbnuyfbwfebqfjkahgfhjwfuwbefwjkfG
tailora.app.jwtExpirationMs=86400000


# =====================================================
# Emcryption Flag
# =====================================================
tailora.req-res.encryption=false
tailora.encrypted.secret=ajhjhfuwfijfkjdd